#!/bin/bash

echo "======================================"
echo "Verifying All Fixes"
echo "======================================"
echo ""
echo "This script verifies:"
echo "1. Scenario names are displayed correctly (not 'a')"
echo "2. Format is: ScenarioName_Iteration<number>"
echo "3. Sequential mode runs with single browser"
echo "4. No retry delays on failures"
echo ""
echo "Expected scenario names in report:"
echo "- Deliberately failing test to demonstrate failure reporting_Iteration1"
echo "- Deliberately failing test to demonstrate failure reporting_Iteration2"
echo "- Deliberately failing test to demonstrate failure reporting_Iteration3"
echo "- Multiple login attempts_Iteration1"
echo "- Multiple login attempts_Iteration2"
echo "- Multiple login attempts_Iteration3"
echo "- Simple login test"
echo "- Invalid login test"
echo "- Demonstrating utility steps"
echo "- Same steps with different keywords"
echo ""
echo "Running test with parallel='none' (sequential mode)..."
echo "======================================"

# Run the test
mvn clean test -DsuiteXmlFile=suites/orangehrm-failure-test.xml

echo ""
echo "======================================"
echo "Test execution completed!"
echo ""
echo "Please verify in the HTML report:"
echo "1. Open: target/cs-reports/cs-test-report.html"
echo "2. Check Test Suite tab for correct scenario names"
echo "3. Format should be: ScenarioName_Iteration<number>"
echo "4. NOT showing 'a_Iteration1', 'a_Iteration2', etc."
echo "======================================" 